# =============================================
# Build config
# =============================================

root:             dist

# Site destination
dest:             <%= settings.root %>

# Documentation
doc:              doc

# Data
data:             data/*.{json,yml}

#Assets
assets:           assets

# Scripts
scripts:          assets/js

# Tests
tests:            tests

# Style
style:            assets/sass

#Components
components:       components

atoms:            <%= settings.components %>/atoms
molecules:        <%= settings.components %>/molecules
organisms:        <%= settings.components %>/organisms
templates:        <%= settings.components %>/templates

#Layout
partials:         <%= settings.components %>/_partials
layouts:          <%= settings.components %>/_layouts
layout:           default.hbs

# Extensions
helpers:          <%= settings.components %>/_helpers/**/*.js