# =============================================
# Site config
# =============================================

title:            Atomic Design Boilerplate
description:      A boilerplate with focus on atomic design principles
author:           yonas.sandbaek@creuna.no
