# =============================================
# Site config
# =============================================

title:            Atomic Mockup Library
description:      An atomic mockup system for frontenders
author:           yonas.sandbaek@creuna.no
